// src/routes/signin.tsx
import { createFileRoute, redirect } from "@tanstack/react-router";
import { type ComponentProps } from "react";
import authClient from "~/lib/auth-client";
import { Button } from "~/lib/components/ui/button";
import { cn } from "~/lib/utils";

const REDIRECT_URL = "/app";

export const Route = createFileRoute("/signin")({
  component: AuthPage,
  beforeLoad: async ({ context }) => {
    if (context.user?.setup_at) {
      throw redirect({
        to: "/app",
      });
    } else if (context.user) {
      throw redirect({
        to: "/setup",
      });
    }
  },
});

function AuthPage() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <div className="bg-card flex flex-col items-center gap-8 rounded-xl border p-10">
        Varo
        <div className="flex flex-col gap-2">
          <SignInButton
            provider="discord"
            label="Discord"
            className="bg-[#5865F2] hover:bg-[#5865F2]/80"
          />
          <SignInButton
            provider="github"
            label="GitHub"
            className="bg-neutral-700 hover:bg-neutral-700/80"
          />
          <SignInButton
            provider="google"
            label="Google"
            className="bg-[#DB4437] hover:bg-[#DB4437]/80"
          />
        </div>
      </div>
    </div>
  );
}

interface SignInButtonProps extends ComponentProps<typeof Button> {
  provider: "discord" | "google" | "github";
  label: string;
}

function SignInButton({ provider, label, className, ...props }: SignInButtonProps) {
  return (
    <Button
      onClick={() =>
        authClient.signIn.social({
          provider,
          callbackURL: REDIRECT_URL,
        })
      }
      type="button"
      size="lg"
      className={cn("text-white hover:text-white", className)}
      {...props}
    >
      Sign in with {label}
    </Button>
  );
}

// app/pages/signin.vue
<script setup lang="ts">
definePageMeta({
    middleware: ['guest-only']
})

const { signIn } = useAuth();
</script>

<template>
    <div class="flex min-h-screen items-center justify-center">
        <div class="flex flex-col items-center gap-8 rounded-xl border bg-muted p-10">
            Logo here
            <div class="flex flex-col gap-2">
                <button
                    class="py-2 px-4 bg-slate-950 transition-colors text-white w-fit hover:bg-slate-800 rounded-md"
                    @click="signIn('github')"
                >
                    Sign in with GitHub
                </button>
                <button
                    class="py-2 px-4 bg-slate-950 transition-colors text-white w-fit hover:bg-slate-800 rounded-md"
                    @click="signIn('google')"
                >
                    Sign in with Google
                </button>
                TODO: email/magic links?
            </div>
        </div>
    </div>
</template>
