// app/routes/signin.tsx
import { createFileRoute, redirect } from "@tanstack/react-router";
import { Discord } from "~/components/icons/Discord";
import { Github } from "~/components/icons/Github";
import { Google } from "~/components/icons/Google";
import { Button } from "~/components/ui/button";

export const Route = createFileRoute("/signin")({
  component: AuthPage,
  beforeLoad: async ({ context }) => {
    if (context.user) {
      throw redirect({
        to: "/app",
      });
    }
  },
});

export default function AuthPage() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <div className="flex flex-col items-center gap-8 rounded-xl border bg-muted p-10">
        Varo
        <form method="GET" className="flex flex-col gap-2">
          <Button
            className="bg-[#5865F2] text-white hover:bg-[#5865F2]/80"
            formAction="/api/auth/discord"
            type="submit"
            size="lg"
          >
            <Discord className="mr-2 size-4" />
            Login with Discord
          </Button>
          <Button
            className="bg-[#333333] text-white hover:bg-[#333333]/80"
            formAction="/api/auth/github"
            type="submit"
            size="lg"
          >
            <Github className="mr-2 size-4" />
            Login with GitHub
          </Button>
          <Button
            className="bg-[#DB4437] text-white hover:bg-[#DB4437]/80"
            formAction="/api/auth/google"
            type="submit"
            size="lg"
          >
            <Google className="mr-2 size-4" />
            Login with Google
          </Button>
        </form>
      </div>
    </div>
  );
}

// app/pages/signin.vue
<script setup lang="ts">
definePageMeta({
	middleware: ["guest-only"],
});
</script>

<template>
	<div class="flex min-h-screen items-center justify-center">
		<div class="flex flex-col items-center gap-8 rounded-xl border bg-zinc-900 p-10">
			Login to varo.dev (WIP!!!!)
			<form method="GET" class="flex flex-col gap-2">
				<button
					type="submit"
					formaction="/api/auth/github"
					class="w-fit rounded-md bg-zinc-50 px-4 py-2 text-zinc-900 transition-colors hover:bg-zinc-300"
				>
					Sign in with GitHub
				</button>
			</form>
		</div>
	</div>
</template>
